In [1]:
import numpy as np


In [2]:
li=["one",2,3,4]
li

['one', 2, 3, 4]

In [3]:
arr=np.array(li)
arr

array(['one', '2', '3', '4'], dtype='<U21')

In [1]:
li


NameError: name 'li' is not defined

In [3]:
print(arr)

NameError: name 'arr' is not defined

In [4]:
# when we have differnt data types in list at that time numpy

In [6]:
sal=[10000,30000,70000,890000]
sal2=[]
for x in sal:
    sal2.append(x+5000)
print(sal2)

[15000, 35000, 75000, 895000]


In [8]:
import numpy as np
salary=np.array(sal)
newsal=[]
newsal.append(salary+5000)
print(newsal)

[array([ 15000,  35000,  75000, 895000])]


In [9]:
print(type(salary))

<class 'numpy.ndarray'>


In [10]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr1=np.zeros((4,4))
print(arr1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
arr=np.ones((4,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [15]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [16]:
arr2=np.ones((4,4))
arr2.shape

(4, 4)

In [17]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
arr2.size

16

In [19]:
arr2.dtype

dtype('float64')

In [21]:
arr=np.array([12,3,4,6,24,56,35])
arr

array([12,  3,  4,  6, 24, 56, 35])

In [22]:
np.sum(arr)

np.int64(140)

In [23]:
print(np.mean(arr))

20.0


In [24]:
print(arr[:4])

[12  3  4  6]


In [26]:
print(np.mean(arr[:4]))

6.25


In [27]:
np.max(arr)

np.int64(56)

In [28]:
np.std(arr)

np.float64(18.291293791621975)

In [29]:
a1=np.array([1,23,4,5])
a2=np.array([12,6,7,8])
a1+a2

array([13, 29, 11, 13])

In [30]:
a1*a2

array([ 12, 138,  28,  40])

In [31]:
sal=np.array([3000,4000,3999])
print(sal*0.11)

[330.   440.   439.89]


In [32]:
np.random.rand(5)

array([0.71459629, 0.69363599, 0.49952907, 0.97187707, 0.42468795])

In [33]:
np.random.randint(1,100,6)

array([41, 25, 54, 90, 81, 72], dtype=int32)

In [1]:
np.random.randint(1,100,10)

NameError: name 'np' is not defined

In [6]:
import numpy as np
arr=np.random.randint(1,101,10)
print(arr)

[82 89 80 93 16 73 11 77 89 41]


In [7]:
print(arr+10)

[ 92  99  90 103  26  83  21  87  99  51]


In [8]:
total=np.sum(arr)
percentage=(total/1000)*100

In [9]:
print(percentage)

65.10000000000001
